name: maheshwari_motors_app
description: "Maheshwari Motors Inventory Management System and Billing Software Application"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  dio: ^5.9.1
  flutter_secure_storage: ^10.0.0
  get: ^4.7.3
  google_fonts: ^8.0.1
  image_picker: ^1.2.1
  intl: ^0.20.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
